name: webdriver
version: 0.12.0.0
license: BSD3
license-file: LICENSE
author: Adam Curtis <kallisti.dev@gmail.com>
maintainer: Tom McLaughlin <tom@codedown.io>
github: "haskell-webdriver/haskell-webdriver"
category: Web, Browser, Testing, WebDriver, Selenium
synopsis: a Haskell client for the Selenium WebDriver protocol
description: |
  A Selenium WebDriver client for Haskell.
  You can use it to automate browser sessions
  for testing, system administration, etc.

  For more information about Selenium itself, see
  <http://seleniumhq.org/>

  To find out what's been changed in this version and others,
  see the change log at
  <https://github.com/haskell-webdriver/haskell-webdriver/blob/main/CHANGELOG.md>

tested-with:
- GHC == 8.6.5
- GHC == 8.8.4
- GHC == 8.10.7
- GHC == 9.0.2
- GHC == 9.2.8
- GHC == 9.4.8
- GHC == 9.6.4

extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wredundant-constraints
  - -Wunused-packages
  dependencies:
  - aeson >= 1.4.1.0 && <2.3
  - attoparsec >= 0.10
  - attoparsec-aeson >=2.1.0.0 && <2.3
  - base == 4.*
  - base64-bytestring >= 1.0
  - bytestring >= 0.9
  - call-stack
  - data-default-class
  - directory > 1.0
  - directory-tree >= 0.11
  - exceptions >= 0.4
  - filepath > 1.0
  - http-client >= 0.3
  - http-types >= 0.8
  - network-uri >= 2.6
  - pretty-simple
  - safe-exceptions
  - scientific >= 0.2
  - string-interpolate
  - temporary >= 1.0
  - text >= 0.11.3
  - time > 1.0
  - transformers >= 0.4
  - unordered-containers >= 0.1.3
  - zip-archive >= 0.1.1.8
  exposed-modules:
  - Test.WebDriver
  - Test.WebDriver.Capabilities
  - Test.WebDriver.Chrome.Extension
  - Test.WebDriver.Class
  - Test.WebDriver.Commands
  - Test.WebDriver.Commands.Internal
  - Test.WebDriver.Commands.Wait
  - Test.WebDriver.Common.Keys
  - Test.WebDriver.Common.Profile
  - Test.WebDriver.Config
  - Test.WebDriver.Cookies
  - Test.WebDriver.Exceptions
  - Test.WebDriver.Exceptions.Internal
  - Test.WebDriver.Firefox.Profile
  - Test.WebDriver.Internal
  - Test.WebDriver.JSON
  - Test.WebDriver.Monad
  - Test.WebDriver.Session
  - Test.WebDriver.Session.History
  - Test.WebDriver.Types
  - Test.WebDriver.Utils

tests:
  tests:
    main: Main.hs
    source-dirs:
    - tests
    ghc-options:
    - -threaded
    - -Wall
    - -Wredundant-constraints
    - -Wunused-packages
    dependencies:
    - aeson
    - base
    - bytestring
    - exceptions
    - filepath
    - http-client
    - http-types
    - monad-logger
    - mtl
    - network
    - optparse-applicative
    - safe
    - safe-exceptions
    - sandwich >= 0.3.0.1
    - sandwich-contexts
    - string-interpolate
    - temporary
    - text
    - unliftio-core
    - unliftio
    - vector
    - wai-app-static
    - warp
    - webdriver
    build-tools: sandwich:sandwich-discover
