
resolver: lts-22.20

packages:
- '.'

nix:
  pure: false
  packages:
  - pkg-config
  - zlib

extra-deps:
- git: https://github.com/codedownio/sandwich
  commit: ef0bb345b07ec89fe526b9348db0a9d02fbf666d
  subdirs:
  - sandwich
  - sandwich-contexts
