
resolver: lts-22.39

packages:
- '.'

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - zlib

extra-deps:
- git: https://github.com/codedownio/sandwich
  commit: b3eef612aa3d083b0d2a588b2c543ee212938668
  subdirs:
  - sandwich
  - sandwich-contexts

# - /home/tom/tools/sandwich/sandwich
# - /home/tom/tools/sandwich/sandwich-contexts
