
resolver: nightly-2025-06-29

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -hiedir .hie
    -dumpdir .ghcdump
    -Wredundant-constraints
    -j8

packages:
- '.'

nix:
  pure: false
  packages:
  - pkg-config
  - zlib
