
resolver: lts-22.39

packages:
- '.'

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - zlib

extra-deps:
- git: https://github.com/codedownio/sandwich
  commit: e295a2e93f1dc03d8c31eb78f4efb74ea6720fbb
  subdirs:
  - sandwich
  - sandwich-contexts

# - /home/tom/tools/sandwich/sandwich
# - /home/tom/tools/sandwich/sandwich-contexts
