
resolver: nightly-2025-12-25

packages:
- '.'

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  commit: ade66e123f6beab5f340193c61c3791c0cc2d8f7
  subdirs:
  - sandwich
  - sandwich-contexts

- vty-windows-0.2.0.3
