
resolver: nightly-2025-12-25

nix:
  enable: false

system-ghc: true

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -hiedir .hie
    -dumpdir .ghcdump
    -Wredundant-constraints
    -j8

packages:
- '.'
