
resolver: lts-22.43

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -hiedir .hie
    -dumpdir .ghcdump
    -Wredundant-constraints
    -j8

packages:
- '.'

nix:
  pure: false
  packages:
  - pkg-config
  - zlib

extra-deps:
- git: https://github.com/codedownio/sandwich
  commit: ade66e123f6beab5f340193c61c3791c0cc2d8f7
  subdirs:
  - sandwich
  - sandwich-contexts

- vty-windows-0.2.0.3
